build

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -52,7 +52,8 @@ jobs:
 
     - name: Merge Main to gh-pages
       run: |
-        git merge origin/main --allow-unrelated-histories --no-ff --commit --no-edit
+        git merge origin/main --allow-unrelated-histories --no-ff --commit --no-edit || (echo "Merge conflict detected. Aborting..." && exit 1)
+
 
     - name: Deploy to GitHub Pages
       run: npm run deploy
